var SNSExpressionData = {
		DEFAULT:{
			name:SNS_I18N.Default,
			priority:0,
			folder:"res/skin/default/icons/expression/default",
			data:[{actionData:"[:草泥马]"  ,url:"shenshou_org.gif"},
					{actionData:"[:神马]"   ,url:"horse2_org.gif"},
					{actionData:"[:浮云]"   ,url:"fuyun_org.gif"},
					{actionData:"[:给力]"   ,url:"geili_org.gif"},
					{actionData:"[:围观]"   ,url:"wg_org.gif"},
					{actionData:"[:威武]"   ,url:"vw_org.gif"},
					{actionData:"[:熊猫]"   ,url:"panda_org.gif"},
					{actionData:"[:兔子]"   ,url:"rabbit_org.gif"},
					{actionData:"[:奥特曼]"   ,url:"otm_org.gif"},
					{actionData:"[:囧]"   ,url:"j_org.gif"},
					{actionData:"[:互粉]"   ,url:"hufen_org.gif"},
					{actionData:"[:礼物]"   ,url:"liwu_org.gif"},
					{actionData:"[:呵呵]"   ,url:"smilea_org.gif"},
					{actionData:"[:嘻嘻]"   ,url:"tootha_org.gif"},
					{actionData:"[:哈哈]"   ,url:"laugh.gif"},
					{actionData:"[:可爱]"   ,url:"tza_org.gif"},
					{actionData:"[:可怜]"   ,url:"kl_org.gif"},
					{actionData:"[:挖鼻屎]"   ,url:"kbsa_org.gif"},
					{actionData:"[:吃惊]"   ,url:"cj_org.gif"},
					{actionData:"[:害羞]"   ,url:"shamea_org.gif"},
					{actionData:"[:挤眼]"   ,url:"zy_org.gif"},
					{actionData:"[:闭嘴]"   ,url:"bz_org.gif"},
					{actionData:"[:鄙视]"   ,url:"bs2_org.gif"},
					{actionData:"[:爱你]"   ,url:"lovea_org.gif"},
					{actionData:"[:泪]"   ,url:"sada_org.gif"},
					{actionData:"[:偷笑]"   ,url:"heia_org.gif"},
					{actionData:"[:亲亲]"   ,url:"qq_org.gif"},
					{actionData:"[:生病]"   ,url:"sb_org.gif"},
					{actionData:"[:太开心]"   ,url:"mb_org.gif"},
					{actionData:"[:懒得理你]"   ,url:"ldln_org.gif"},
					{actionData:"[:右哼哼]"   ,url:"yhh_org.gif"},
					{actionData:"[:左哼哼]"   ,url:"zhh_org.gif"},
					{actionData:"[:嘘]"   ,url:"x_org.gif"},
					{actionData:"[:衰]"   ,url:"cry.gif"},
					{actionData:"[:委屈]"   ,url:"wq_org.gif"},
					{actionData:"[:吐]"   ,url:"t_org.gif"},
					{actionData:"[:打哈欠]"   ,url:"k_org.gif"},
					{actionData:"[:抱抱]"   ,url:"bba_org.gif"},
					{actionData:"[:怒]"   ,url:"angrya_org.gif"},
					{actionData:"[:疑问]"   ,url:"yw_org.gif"},
					{actionData:"[:馋嘴]"   ,url:"cza_org.gif"},
					{actionData:"[:拜拜]"   ,url:"88_org.gif"},
					{actionData:"[:思考]"   ,url:"sk_org.gif"},
					{actionData:"[:汗]"   ,url:"sweata_org.gif"},
					{actionData:"[:困]"   ,url:"sleepya_org.gif"},
					{actionData:"[:睡觉]"   ,url:"sleepa_org.gif"},
					{actionData:"[:钱]"   ,url:"money_org.gif"},
					{actionData:"[:失望]"   ,url:"sw_org.gif"},
					{actionData:"[:酷]"   ,url:"cool_org.gif"},
					{actionData:"[:花心]"   ,url:"hsa_org.gif"},
					{actionData:"[:哼]"   ,url:"hatea_org.gif"},
					{actionData:"[:鼓掌]"   ,url:"gza_org.gif"},
					{actionData:"[:晕]"   ,url:"dizzya_org.gif"},
					{actionData:"[:悲伤]"   ,url:"bs_org.gif"},
					{actionData:"[:抓狂]"   ,url:"crazya_org.gif"},
					{actionData:"[:黑线]"   ,url:"h_org.gif"},
					{actionData:"[:阴险]"   ,url:"yx_org.gif"},
					{actionData:"[:怒骂]"   ,url:"nm_org.gif"},
					{actionData:"[:心]"   ,url:"hearta_org.gif"},
					{actionData:"[:伤心]"   ,url:"unheart.gif"},
					{actionData:"[:猪头]"   ,url:"pig.gif"},
					{actionData:"[:ok]"   ,url:"ok_org.gif"},
					{actionData:"[:耶]"   ,url:"ye_org.gif"},
					{actionData:"[:good]"   ,url:"good_org.gif"},
					{actionData:"[:不要]"   ,url:"no_org.gif"},
					{actionData:"[:赞]"   ,url:"z2_org.gif"},
					{actionData:"[:来]"   ,url:"come_org.gif"},
					{actionData:"[:弱]"   ,url:"sad_org.gif"},
					{actionData:"[:蜡烛]"   ,url:"lazu_org.gif"},
					{actionData:"[:钟]"   ,url:"clock_org.gif"},
					{actionData:"[:话筒]"   ,url:"m_org.gif"},
					{actionData:"[:蛋糕]"   ,url:"cake.gif"}
			]
		}
}